### PR TITLE
Adding json file with (only) all of the resourceTemplates

### PR DESCRIPTION
**Pull request by jgreben**
We will need this data available to be able to spoof the call for (only) resource templates (without the Profile wrapping). We want to just use webpack for builds and server (without using Express). Webpack does not play nicely with fetching data from a filesystem.

This repo also contains a combined array of Profiles file that can be parsed to pull out the resourceTemplates. This can be done using `jq` https://stedolan.github.io/jq/ and the following query:

`cat all_profiles.json | jq 'map(.Profile | del(.contact) | del(.date) | del(.description) | del(.id) | del(.title))'`

Closes LD4P/sinopia_editor#163

### CODE REVIEW

**Comment by jgreben** [comment]
@cmh2166 care to review?

**Comment by cmharlow** [comment]
Finally getting to this, looking now

**Comment by cmharlow** [comment]
Question: why the `v1` directory or instances versioning in that way? Just curious about the selection.

**Comment by cmharlow** [comment]
I have some proposals for this, but the sample file makes sense. Will have my proposals + questions in a follow up PR.

**Pull request merged**
