### PR TITLE
Adding skeleton of profile json-schema for wip pr

### PR DESCRIPTION
**Pull request by cmharlow**
Making a PR for ease of linking, review, sharing

### CODE REVIEW

**Comment by cmharlow** [comment]
I will squash / clean up this commit history when PR is ready for merging. Right now, reflects save points between validation against all LC verso profiles & templates.

**Comment by ndushay** [comment]
It's possible we can leverage "dependencies" in the JSON schema (https://json-schema.org/understanding-json-schema/reference/object.html#dependencies) to enforce specific properties appearing or not appearing for a given propertyTemplate "type".

Also note that my spelunking through existing resourceTemplates has surfaced some additional attributes in propertyTemplates than those represented here.  (though I'm not sure those additional attributes are useful and/or used by BFE)

**Comment by cmharlow** [comment]
Note: had to rebase + do some merging magic to get master back into here; also, the profiles aren't currently valid against the specs, but the failure is understandable so we can work off of it.

**Review by ndushay — APPROVED** [review]
I have a number of changes planned for the propertyTemplate json schema, but that is for a future PR.

**Pull request merged**
